function config = getConfig()
%getConfig controls the parameters for the simulation and stores them in a
%struct
radius = 1;
config = struct(...
    'headshape',    struct('radius', radius), ...
    'sensorArray',  struct('arrangement', 'grid', ...
                           'multiR'     , false, ...
                           'numTheta'   , 40, ...
                           'numPhi'     , 100, ...
                           'thetaRange' , [0, pi], ...
                           'phiRange'   , [0, 2*pi]), ...
    'constants',    struct('k', Constants.k, 'eps0', 1), ...
    'dipoleParams', struct( ...
        'momentType',     'radial', ...
        'momentMagnitude', 1e-02, ...
        'numDips',         7, ...
        'rRange',          radius*[.8, .9], ...
        'thetaRange',      [pi/6,pi/2], ...
        'phiRange',        [pi, 3*pi/2] ...
        ), ...
    'interpolationParams', struct('method', 'natural', 'extrapolation', 'linear'), ...
    'seed', 1234 ...
    );

dTheta = abs(config.sensorArray.thetaRange(2)-config.sensorArray.thetaRange(1)) / config.sensorArray.numTheta;
dPhi = abs(config.sensorArray.phiRange(2)-config.sensorArray.phiRange(1)) / config.sensorArray.numPhi;
%config.sensorArray.thetaRange(1) = config.sensorArray.thetaRange(1) + dTheta;
config.sensorArray.phiRange(2) = config.sensorArray.phiRange(2) - dPhi;
config.sensorArray.numSensors = config.sensorArray.numPhi * config.sensorArray.numTheta;
% config.dipoleParams.rRange = config.headshape.radius * config.dipoleParams.rRange;
end