function config = initializeGridConfig(maxTheta, maxPhi, NTheta, NPhi)
    % Initialize the config struct with precomputed dTheta and dPhi
    config = struct(...
        'maxTheta', maxTheta, ...
        'maxPhi', maxPhi, ...
        'NTheta', NTheta, ...
        'NPhi', NPhi, ...
        'dTheta', maxTheta / NTheta, ...
        'dPhi', maxPhi / NPhi ...
    );
end

% Usage
% config = initializeConfig(pi / 2, 2 * pi, 10, 10);
% disp(config.dTheta);
% disp(config.dPhi);
